config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  get '/about', to: 'home#about', as: 'about'
  get '/service', to: 'home#service', as: 'service'
  get 'contact', to: 'contact#new', as: 'contact'
  post 'contact', to: 'contact#create_mail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController


def new
    @message = Contact.new
  end

  def create_mail
    @message = Contact.new(message_params)
    
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:contact).permit(:name, :email, :mobile, :message)
  end


	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 

  def service
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/new.html.erb
<div class="about-heading">
      <h2>Contact <span>Us</span></h2>
   </div>
   <!-- //about-heading -->
   <!-- contact -->
   <div class="contact">
      <div class="container">
         <div class="agile-contact-form">
            <div class="col-md-6 contact-form-left">
               <div class="w3layouts-contact-form-top">
                  <h3>Get in <span>touch</span></h3>
                  <p>We manufacture Seed Grading Machine which has sturdy structure and long working life. Offering Seed Grading Machine, we are eminent Suppliers catering efficiently to the demands of the customers. Due to our secure and hassle-free payment procedures, clients stay satisfied with us. We undertake both online and offline payment processing methods including cash and bank transfers.</p>
               </div>
               <div class="agileits-contact-address">
                  <ul>
                     <li><i class="fa fa-phone" aria-hidden="true"></i> <span>+91 8989104583</span></li>
                     <li><i class="fa fa-phone fa-envelope" aria-hidden="true"></i> <span><a href="mailto:example@email.com">veerorganics@gmail.com</a></span></li>
                     <li><i class="fa fa-map-marker" aria-hidden="true"></i> <span>224,Teachers Colony, Neemuch(M.P) 458441</span></li>
                  </ul>
               </div>
            </div>
            <div class="col-md-6 contact-form-right">
               <div class="contact-form-top">
                  <h3>Send us a <span>message</span></h3>
               </div>
               <div class="agileinfo-contact-form-grid">
                   <%= form_for @message, :class=>"contact", url: contact_path do |message_form| %>
                   <%= message_form.text_field :name, :class=> "form-control", placeholder: "Name" %>
                   <%= message_form.email_field :email, :class=>"form-control", placeholder: "Email"%>
                   <%= message_form.text_field :mobile, :class=> "form-control", placeholder: "Mobile Number" %>
                   <%= message_form.text_area :message, :class=> "form-control",  placeholder: "Message"%>
                   <%= message_form.submit "Submit", :class => "btn1"%>
                  <% end %>
               </div>
            </div>
            <div class="clearfix"> </div>
         </div>
         
         <div class="w3agile-map">
            <h3>Find us <span>here</span></h3>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3631.5586873994694!2d74.86789735021105!3d24.46609198416413!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3966737f6429b6cb%3A0x4f6bb66df49242d3!2sshree+veer+organics+agro+india+pvt.+ltd.!5e0!3m2!1sen!2sin!4v1506592349655" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
         </div>
      </div>
   </div>
   

app/views/contact/new_message.html.erb
<% debugger %>
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Name:  <%= @name %></h3>
    <p>
      Email:  <%= @email %>.<br>
    </p>
    <p>
      Subject: <%= @subject %>.
    </p>
    <p>Message : <%= @msg %></p>
  </body>
</html>

app/views/home/about.html.erb
	<div class="about-heading">
		<h2>About <span>Us</span></h2>
	</div>

	<div class="about">
		<!-- about-top -->
		<div class="agileits-about-top">
			<div class="container">
				<div class="w3-banner-bottom-heading">
					<h3>Who we <span>are</span></h3>
				</div>
				<div class="agileinfo-top-grids">
					<div class="col-sm-4 wthree-top-grid">
						<img src="../assets/ma.jpg" alt="" />
						
<p>We manufacture Seed Grading Machine which has sturdy structure and long working life. Offering Seed Grading Machine, we are eminent Suppliers catering efficiently to the demands of the customers. Due to our secure and hassle-free payment procedures, clients stay satisfied with us. We undertake both online and offline payment processing methods including cash and bank transfers.</p>
					</div>
					<div class="col-sm-4 wthree-top-grid">
					<img src="../assets/ss.jpg" alt="" />
						
<p>The company has good working machines.The start-up activity was trading and re-packing of various products.Our expertise lies in marketing wide array of seeds.Further The clients can avail from us at very nominal price.</p>
						</div>
		<div class="col-sm-4 wthree-top-grid">
				<img src="../assets/ws.jpg" alt="" />
						
<p>We firmly believe that quality has to be given prime importance in order to achieve trust of the clients. We use wel equippted machines to make our  Products that are extracted from us. which make us assure an eco friendly range.</p>
					
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
		<!-- //about-top -->
		
		<!-- choose -->
		<div class="jarallax w3-agileits-choose-grid">
			<div class="container">
				<div class="w3-banner-bottom-heading about-choose">
					<h3>Why choose  <span>us?</span></h3>
				</div>
				<div class="agile-choose-grids">
					<div class="col-sm-4 agile-choose-grid">
						<div class="choose-icon">
							<i class="fa fa-user" aria-hidden="true"></i>
						</div>
						<div class="choose-info">
							<h5>OUR MISSION</h5>
							<p>Our good agriculture seeds enable differentiation in product quality and farmer yields. In order to enable between harvesting and processing, we also provide last mile pick-ups at fields. Sustainable agriculture practices result in environmental protection and safe products for our customers and end-consumers.</p>
						</div>
					</div>
					<div class="col-sm-4 agile-choose-grid">
						<div class="choose-icon">
							<i class="fa fa-cogs" aria-hidden="true"></i>
						</div>
						<div class="choose-info">
							<h5>OUR VISION </h5>
							<p>The best growing areas for various crops have been identified based on years of experience.  The best quality of products are supplied.we positively impact local economies and stakeholders such as farm workers and staff .</p>
						</div>
					</div>
					<div class="col-sm-4 agile-choose-grid">
						<div class="choose-icon">
							<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
						</div>
						<div class="choose-info">
							<h5>WHAT WE DO</h5>
							<p>We source and provide farmers the highest quality seeds that are suitable for growing in particular climatic conditions to produce yields that to quality standards that meet our customer requirements. 
                            </p>
						</div>
					</div>
				</div>	
			</div>
		</div>
		<!-- //choose -->
		
		<!-- team -->
		<div class="team">
			<div class="container">
				<div class="w3-banner-bottom-heading">
					<h3>Our <span>Team</span></h3>
				</div>
				<div class="team-grids">
					<!-- Bottom to top-->
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/kishor.jpg" alt="img" /></div>
								<div class="info">
									<h3>Kishor Dhakad</h3>
									<div class="icons">
										<ul>
											<li><a href="https://www.facebook.com/profile.php?id=100009382944124"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/ravi.png" alt="img" /></div>
								<div class="info">
									<h3>Ravi Dhakad</h3>
									<div class="icons">
										<ul>
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/arvind.jpg" alt="img" /></div>
								<div class="info">
									<h3>Arvind Dhakad</h3>
									<div class="icons">
										<ul>
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/pushkar.png" alt="img" /></div>
								<div class="info">
									<h3>Pushkar Dhakad</h3>
									<div class="icons">
										<ul>
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/rahul.jpg" alt="img" /></div>
								<div class="info">
									<h3>Rahul Dhakad</h3>
									<div class="icons">
										<ul>
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="col-sm-4 team-grid">
							<!-- normal -->
							<div class="ih-item circle effect10 bottom_to_top">
								<div class="img"><img src="../assets/sunita.jpg" alt="img" /></div>
								<div class="info">
									<h3>Sunita Patidar</h3>
									<div class="icons">
										<ul>
											<li><a href="https://www.facebook.com/sunni.sanghvi"><i class="fa fa-facebook"></i></a></li>
											<li class="team-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- end normal -->
						</div>
						<div class="clearfix"> </div>
					<!-- end Bottom to top-->
				</div>
			</div>
		</div>
		<!-- //team -->
	</div>
	<!-- //about -->

app/views/home/service.html.erb
<div class="about-heading">
		<h2>Our <span>Services</span></h2>
	</div>
	<!-- //about-heading -->
	<!-- services -->
	<div class="services">
		<!-- best-services -->
		<div class="w3-best-services">
			<div class="container">
				<div class="w3-banner-bottom-heading">
					<h3>Best <span>Services</span></h3>
				</div>
				<div class="w3l-best-services-grids">
					<div class="servc-grids">
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-asterisk effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Tested Products</h4>
								<p>We deliver the product to our cleint only when we test and it is best for delivery</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-road effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Techologies</h4>
								<p>New technologies are used so that we can provide the best to the customer </p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="servc-grids">
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-plane effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Import And Export</h4>
								<p> Export marketing is done directly and also  merchant exporters.Offered collections of these products are made by employing qualitative ingredients and progressive technology.  </p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-bed effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Our Research Team</h4>
								<p>We have  wide experience in research and development in technology. Our team works in a team spirit and assists us in processing array of Products. </p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="servc-grids">
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-magnet effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Client Satisfaction</h4>
								<p> Company work for the satisfaction of the customer.Because we can get success only when our customer will support us.      </p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="col-md-6 servc-grid">
							<div class="col-xs-3 servc-grid-left">
								<span class="glyphicon glyphicon-globe effect-1" aria-hidden="true"></span>
							</div>
							<div class="col-xs-9 servc-grid-right">
								<h4>Our Instructors</h4>
								<p>Great instructor who always guide us and direct us.</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
		</div>
		<!-- //best-services -->
		<!-- featured-services -->
		<div class="w3ls-featured-services">
			<div class="container">
				<div class="col-md-6 agileits-featured-left">
					<div class="w3-banner-bottom-heading featured-heading">
						<h3>Featured <span>Services</span></h3>
					</div>
					<div class="w3-agileits-featured-left-grids">
						<div class="w3-agileits-featured-left-grid">
							<div class="col-sm-4 featured-left-img">
								<img src="../assets/mc1.jpg" alt="" />
							</div>
							<div class="col-sm-8 featured-left-text">
								<h5>New Technology Machines</h5>
								<p>We are using new Technology machines for filtering the seed.</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-agileits-featured-left-grid">
							<div class="col-sm-4 featured-left-img">
								<img src="../assets/ss.jpg" alt="" />
							</div>
							<div class="col-sm-8 featured-left-text">
								<h5>Exporting Facility</h5>
								<p>We are also having a good quality seeds that are exported at wide range.</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="w3-agileits-featured-left-grid">
							<div class="col-sm-4 featured-left-img">
								<img src="../assets/wa.jpg" alt="" />
							</div>
							<div class="col-sm-8 featured-left-text">
								<h5>Packing Of Seed</h5>
								<p>Supplying a wel packed item to the customer .</p>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
				<div class="col-md-6 agileits-news-right">
					<div class="w3-banner-bottom-heading featured-heading">
						<h3>Latest <span>News</span></h3>
					</div>
					<div class="agile-news-grids">
						<div class="agile-news-grid">
							<div class="agile-news-date">
								<h5>24</h5>
								<p>Sept-17</p>
							</div>
							<div class="agile-news-text">
								<h5><a href="single.html">Best Pricing</a></h5>
								<p>At very reasonable price we provide seed to customer which be easy affordable by customers  .</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="agile-news-grid">
							<div class="agile-news-date">
								<h5>10</h5>
								<p>Aug-17</p>
							</div>
							<div class="agile-news-text">
								<h5><a href="single.html">Customer requirement</a></h5>
								<p>Firstly we see the customers requirement that which type of seed they want for there use.</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="agile-news-grid">
							<div class="agile-news-date">
								<h5>07</h5>
								<p>Sept-17</p>
							</div>
							<div class="agile-news-text">
								<h5><a href="single.html">Customer Feedback </a></h5>
								<p>Customer feedback is obtained on the performance of groups and objectives are reviewed and aligned to customer requirements.</p>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<!-- //featured-services -->
	</div>
	

app/views/layouts/_footer.html.erb
<div class="footer">
		<div class="container">
			<div class="agile-footer-grids">
				<div class="col-md-4 agile-footer-grid">
					<h4>History of <span>Veer Organics</span></h4>
					<p>"Our team of Biofertilizer Specialists and support team include  each have a robust and comprehensive knowledge of our products.we are committed to helping you make the best selection for your farming needs.Providing our cleint the best product for there production."</span></p>
				</div>
				<div class="col-md-4 agile-footer-grid">
					<h4>About<span>Veer Organics</span></h4>
					<ul class="w3agile_footer_grid_list">
						<li><span><i class="fa fa-envelope" aria-hidden="true"></i> veerorganics@gmail.com
   
</span></li>
						<li><span><i class="fa fa-mobile" aria-hidden="true"></i> +91 - 8989104583</span></li>
						<li><span><i class="fa fa-phone" aria-hidden="true"></i> 07423-224583</span></li>
						<li><span><i class="fa fa fa-map-marker" aria-hidden="true"></i> 224,Teachers Colony, Neemuch</span></li>
					</ul>
				</div>
				<div class="col-md-4 agile-footer-grid">
					<h4>Veer Organics <span>Gallery</span></h4>
					<div class="popular-grids">
						<div class="popular-grid">
							<a href="#"><img src="../assets/logo.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc1.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc2.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/9.jpg" alt=""></a>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="popular-grids agileits-w3layouts-popular">
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc3.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc4.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/me.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc5.jpg" alt=""></a>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="popular-grids">
						<div class="popular-grid">
							<a href="#"><img src="../assets/mc6.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mai.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/mai2.jpg" alt=""></a>
						</div>
						<div class="popular-grid">
							<a href="#"><img src="../assets/ks.jpg" alt=""></a>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="copyright">
			<p>© 2017. All rights reserved | Design & Developed by <a href="http://risedigitech.com">Risedigitech</a></p>
		</div>
	</div>
	<!-- //footer -->

app/views/layouts/_header.html.erb
	<div class="header-top">
		<div class="container">
			<div class="w3layouts-address">
				<ul>
					<li><i class="fa fa-mobile" aria-hidden="true"></i> +91 8989104583</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com"> veerorganics@gmail.com</a></li>
				</ul>
			</div>
			<div class="agileinfo-social-grids">
				<ul>
					<li><a href="https://www.facebook.com/veerorganicseeds/"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="https://plus.google.com/u/8/discover"><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#"><i class="fa fa-youtube"></i></a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //header-top -->
	<!-- header -->
	<div class="header">
			<div class="container">
				<nav class="navbar navbar-default">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
					  
						<div class="w3layouts-logo">
							<h1><a href="<%= root_path %>">Shree Veer <span>Organics</span></a></h1>
						</div>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
						<nav>
							<ul class="nav navbar-nav">
								<li class="active"><a href="<%= root_path %>">Home</a></li>
								<li><a href="<%= about_path %>" class="hvr-sweep-to-bottom">About</a></li>
								<li><a href="<%= service_path %>" class="hvr-sweep-to-bottom">Services</a></li>
								<li><a href="<%= contact_path %>" class="hvr-sweep-to-bottom">Conatct Us</a></li>
							</ul>
						</nav>
					</div>
					<!-- /.navbar-collapse -->
				</nav>
			</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VeerOrganics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script>
    <script src='/assets/jquery.immersive-slider.js'></script>
    <script src='/assets/responsiveslides.min.js'></script>
    <script src='/assets/jquery.flexslider.js'></script>
    <script src='/assets/move-top.js'></script>
    <script src='/assets/jquery.flipster.js'></script>
    <script src='/assets/jarallax.js'></script>
  </head>

  <body>
    <div id="wrapper">
    <%= render :partial  => "layouts/header" %>
    <%= yield %>
    <%= render :partial  => "layouts/footer" %>
    </div>
  </body>
</html>